#!/usr/bin/env bash



ns=aks-turbobutton
if ! kubectl get namespace ${ns} 2>/dev/null >/dev/null; then
    kubectl create namespace ${ns}
    sleep 5
fi

kubectl create configmap -n $ns aks-turbobutton --from-file=fix-node.sh -o yaml --dry-run | kubectl replace --force -f -
kubectl apply -f turbobutton.yaml

#helm install tb -f values.yaml stable/prometheus-operator --namespace aks-turbobutton
