#!/usr/bin/env bash
ns=aks-turbobutton
if ! kubectl get ns $ns; then
  kubectl create ns $ns
  while ! kubectl get ns $ns > /dev/null ;do
    sleep 5
  done
fi

kubectl create configmap aks-turbobutton --from-file=fix-node.sh -o yaml --dry-run | kubectl replace -f -
kubectl apply -f turbobutton.yaml
#helm install tb -f values.yaml stable/prometheus-operator --namespace aks-turbobutton
