kind: ConfigMap
apiVersion: v1
metadata:
  name: turbobutton-able-tunas
  namespace: aks-turbobutton
data:
  TUNEDEVS: "1" # If true then we will drop in the tuned rc.local file
  REHOMEIO: "1" # If true the docker/ and kubelet/ directories are moved to tmpfs
  SCHEDULER: "mq-deadline"
  READ_AHEAD_KB: "4096"
  MAX_SECTORS_KB: "128"
  QUEUE_DEPTH: "64" # Need to validate Azure guidance re: qdepth
  INST_BPFTRACE: "1"
  INST_EBPF_EXPORTER: "1"
  INST_FLAMEGRAPH: "1"
  OOMKILLER_OFF: "1"
  TRANSPARENT_HUGEPAGE: "always"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aks-turbobutton
  namespace: aks-turbobutton
  labels:
    k8s-app: aks-turbobutton
spec:
  selector:
    matchLabels:
      name: aks-turbobutton
  template:
    metadata:
      labels:
        name: aks-turbobutton
    spec:
      hostPID: true # For entering the host mont namespace via init
      containers:
      - name: aks-turbobutton
        image: alexeldeib/bpftrace-bin-xenial-llvm-8
        command: ["/scripts/fix-node.sh", "3600"]
        #command: ["/bin/sleep", "3600"]
        envFrom:
        - configMapRef:
            name: turbobutton-able-tunas
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: turbobutton
          mountPath: /scripts
        - name: turbobutton-io
          mountPath: /scripts-io
        - name: procmnt
          mountPath: /procmnt
        - name: etcmnt
          mountPath: /etcmnt
        - name: usrmnt
          mountPath: /usrmnt
        - name: usrlocalmnt
          mountPath: /usrlocalmnt
        - name: cloudmnt
          mountPath: /cloudmnt
        - name: pythonmnt
          mountPath: /pythonmnt
      volumes:
      - name: turbobutton
        configMap:
          name: aks-turbobutton
          defaultMode: 0744
      - name: turbobutton-io
        configMap:
          name: aks-turbobutton-io
      - name: procmnt
        hostPath:
          path: /proc
      - name: etcmnt
        hostPath:
          path: /etc
      - name: usrmnt # im tired ok
        hostPath:
          path: /usr
      - name: usrlocalmnt
        hostPath:
          path: /usr/local
      - name: cloudmnt
        hostPath:
          path: /var/lib/cloud
      - name: pythonmnt
        hostPath:
          path: /usr/lib/python2.7
